apiVersion: apps/v1
kind: Deployment
metadata:
    name: precily
spec:
    selector:
        matchLabels:
            app: precily
    replicas: 2
    template:
        metadata:
            labels:
                app: precily
        spec:
            containers:
                - name: precily
                  imagePullPolicy: Never
                  image: abdulkader4513/precily:latest
                  ports:
                      - containerPort: 5000
                        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: precily
spec:
  type: ClusterIP
  selector:
    app: precily
  ports:
    - protocol: TCP
      port: 5000
#       targetPort: 4000
#       nodePort: 30000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: precily
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  rules:
    - http:
        paths:
          - backend:
              service:
                name: precily
                port:
                  number: 5000
            path: /
            pathType: Prefix
