apiVersion: apps/v1
kind: Deployment
metadata:
    name: precily
spec:
    selector:
        matchLabels:
            app: precily
    replicas: 2
    template:
        metadata:
            labels:
                app: precily
        spec:
            containers:
                - name: precily
                  imagePullPolicy: Never
                  image: abdulkader4513/precily:latest
                  ports:
                      - containerPort: 5000
                        protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
    name: precily
spec:
    type: NodePort
    selector:
        app: precily
    ports:
        - port: 8080
          targetPort: 5000
