apiVersion: apps/v1
kind: Deployment
metadata:
    name: precily
spec:
    selector:
        matchLabels:
            app: precily
    replicas: 2
    template:
        metadata:
            labels:
                app: precily
        spec:
            containers:
                - name: precily
                  imagePullPolicy: Never
                  image: abdulkader4513/precily:latest
                  ports:
                      - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: precily
spec:
  type: LoadBalancer
  selector:
    app: precily
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      nodePort: 30000

