apiVersion: apps/v1
kind: Deployment
metadata:
    name: precily
spec:
    selector:
        matchLabels:
            app: precily
    replicas: 2
    template:
        metadata:
            labels:
                app: precily
        spec:
            containers:
                - name: precily-api
                  imagePullPolicy: Never
                  image: abdulkader4513/precily:latest
                  ports:
                      - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
    name: precily
spec:
  type: NodePort
  selector:
    app: precily
  ports:
  - name: http
    port: 80
    targetPort: 4000
    nodePort: 32140
#     type: NodePort
#     selector:
#         app: precily
#     ports:
#         - port: 4000
#           targetPort: 4000
